#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail


echo "############################################################"
echo "# disable network configuration by cloud-init              #"
echo "############################################################"

tee --append /etc/cloud/cloud.cfg <<EOF
network:
  config: disabled
EOF

