#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail


echo "############################################################"
echo "# Setting DHCP Client ID as HW for CentOS                  #"
echo "############################################################"

echo "send dhcp-client-identifier = hardware;" >> /etc/dhcp/dhclient.conf
